version: "3.9"

services:
  redis:
    ports:
      - 6379:6379

  push_server:
    build:
      context: .
      target: push_server_dev
    volumes:
      - ./:/srv/app
    environment:
      ARCHETHIC_ENDPOINT: http://192.168.1.20:4000
  