# Setup a network of 3 nodes with 3 database, with a metric collection and two services to run benchmarks and validation
#
# # Usage
#
# ## start local network
#
#   $ docker-compose up
#
# ## benchmark network
#
#   $ docker-compose up bench
#
# ## validate network
#
#   $ docker-compose up validate
#

version: "3.9"

volumes:
  db:

services:
  redis:
    image: redis:7
    volumes:
      - db:/data
    ports:
      - 6379:6379
  
  node1:
    build:
      context: .
      target: push_server_prod
    ports:
      - 8200:3000
    depends_on:
      - redis
    environment:
      REDIS_PORT: 6379
      REDIS_HOST: redis
    
