version: "3.9"

services:
  redis:
    ports:
      - 6379:6379

  node1:
    build:
      context: .
      target: push_server_dev
    volumes:
      - ./:/srv/app
  node2:
    build:
      context: .
      target: push_server_dev
    volumes:
      - ./:/srv/app
  node3:
    build:
      context: .
      target: push_server_dev
    volumes:
      - ./:/srv/app
