# Setup a network of 3 nodes with 3 database, with a metric collection and two services to run benchmarks and validation
#
# # Usage
#
# ## start local network
#
#   $ docker-compose up
#
# ## benchmark network
#
#   $ docker-compose up bench
#
# ## validate network
#
#   $ docker-compose up validate
#

version: "3.9"

volumes:
  db:

services:
  ngnix-server:
    image: nginx:1.13
    ports: 
        - "8300:80"
    volumes: 
        - './nginx.conf:/etc/nginx/nginx.conf'
    networks: 
        - "push_server"
    depends_on: 
        - push_server


  redis:
    image: redis:7
    volumes:
      - db:/data
    networks:
      - "push_server"

  push_server:
    build:
      context: .
      target: push_server_prod
    depends_on:
      - redis
    environment:
      PORT: 3000
      REDIS_PORT: 6379
      REDIS_HOST: redis
      ARCHETHIC_ENDPOINT: https://mainnet.archethic.net
    networks:
      - "push_server"
    
networks:
  push_server: